export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'; 
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'; 
export const GET_FILTRATED_CATEGORIES = 'GET_FILTRATED_CATEGORIES'; 
export const RESTART_PRODUCTS = 'RESTART_PRODUCTS'; 



